# Generated by Django 4.1.7 on 2023-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="tag",),
        migrations.AddField(
            model_name="task", name="tag", field=models.ManyToManyField(to="todo.tag"),
        ),
    ]
